### ISSUE TITLE
[BUG] Crash at atartup

### ISSUE THREAD

**Issue by Archilyte** [TicTicBoooom-Mods/MasterfulMachinery#11]
# Version Information
Forge version:  36.1.31
Masterful Machinery version: 0.1.49-B391

ADD ON'S
Optifine version: HD U G8
Botania version:  416
Create version: 0.3.1c
Mekanism version: 10.0.21.448
Pneumaticcraft version: null
Astral Sorcery version: null

# Further Information
Link to crash log: https://gist.github.com/Archilyte/2ca68c9590a2e6a7599f8d096c6bbde2

Steps to reproduce:
1. Load game
2. Crash

What I expected to happen: Game loads normaly

What happened instead: Game crashed

**Comment by liuseniubi** [comment]
Same here. But not in every instances.

**Comment by liuseniubi** [comment]
https://paste.ubuntu.com/p/PHHpWDSrp6/

**Comment by Archilyte** [comment]
note: the crash persists even without optifine

**Comment by SzilBalazs** [comment]
I think this has to do something with language. Is the lang english when its crash?

**Comment by liuseniubi** [comment]
> I think this has to do something with language. Is the lang english when its crash?

I'm using Chinese, I'll give it a try right now.

**Comment by SzilBalazs** [comment]
Where is the MMSetup enum's file? I can't find it.

**Comment by liuseniubi** [comment]
> I think this has to do something with language. Is the lang english when its crash?

Yeah! After using English, it runs correctly.

**Comment by MasterSloth1** [comment]
no longer a issue so closing
