### ISSUE TITLE
Better Wiki

### ISSUE THREAD

**Issue by DariusSG** [TicTicBoooom-Mods/MasterfulMachinery#15]
The wiki does not cover every which it should. 
Example: Output has a chance of being produced, however, wiki does not say anything about it unless people look at the code.

**Comment by ticticboooom** [comment]
closing as we have made it pretty clear that we arew working on one. pls ask in discord before opening issues

**Comment by MasterSloth1** [comment]
http://wiki.ticticboooom.live/en/Masterful_Machinery/Explanations/Recipe
