### ISSUE TITLE
[BUG] crash on startup with new Create version

### ISSUE THREAD

**Issue by DAmNRelentless** [TicTicBoooom-Mods/MasterfulMachinery#17]
# Version Information
Forge version:  36.1.32
Masterful Machinery version: 0.1.50-B476

# ADD ON'S
Optifine version: null
Botania version: 418
Create version: 0.3.2a
Mekanism version: 10.0.21.448
Pneumaticcraft version: 2.13.1-202
Astral Sorcery version: 1.13.12

# Further Information
Link to crash log: https://pastebin.com/mudrPgLC
Steps to reproduce:
1. update to newest version of Create
2. start the game
3. game crashes

What I expected to happen:
Game should run fine.

What happened instead:
Startup crash with newest Create version.

**Comment by ticticboooom** [comment]
can yopu upload your entire log file not just the crash report from the event of the crash

**Comment by DAmNRelentless** [comment]
full log https://pastebin.com/wj08Vxz9

**Comment by ticticboooom** [comment]
closing as i am, pretty sure this is an issue with Create additions mod as that is what is hard erroring before the MM crash, MM is just in the crash report.

**Comment by ticticboooom** [comment]
have run test, it is create crafts and additions

**Comment by Zarvera** [comment]
I don't really understand how it's Create: Crafts and Additions problem when said mod runs absolutely fine along 160 other mods in my current testpack with 0 problems, yet as soon as Masterful Machinery is added it all crashes complaining about "masterfulmachinery:projector" not being registered. 

I'm fairly sure you are misreading the logs as it's most definitely a problem on MM side.

**Comment by Jerome226** [comment]
I have Create Craft and Addition, MM and my game works fines, looks like it's not MM and/or Create Crafts and additions

**Comment by HopsandBarley** [comment]
I am getting a crash with the newest version of Create on my pack as well, and I dont have MM installed.  I do have Create Crafts & additions installed.  But I can also verify that it's no MM causing the issue

**Comment by ticticboooom** [comment]
please update to the latest version of MM, i should have fixed it in 0.1.51

**Comment by Zarvera** [comment]
I had 0.1.51 already, however C&C turned out to have a sneaky beta version pushed and curse app failed to show update, but yeah updating C&C to the latest version resolved the issue, i'm not crashing on startup anymore.

**Comment by HopsandBarley** [comment]
Silly hidden beta version of Create Crafts and Additions was my problem as well.  Good catch Zarvera.
