### ISSUE TITLE
[BUG] Mekanism Gas Output Port set to Input instead of Output

### ISSUE THREAD

**Issue by jgrimes900** [TicTicBoooom-Mods/MasterfulMachinery#18]
# Version Information
Forge version:  36.1.33
Masterful Machinery version: 1.16.5-0.1.52-B671

ADD ON'S
Optifine version: null
Botania version:  null
Create version: null
Mekanism version: 1.16.5-10.0.21.448
Pneumaticcraft version: null
Astral Sorcery version: 1.16-1.16.5-1.13.12

# Further Information
Link to latest.log: [pastebin](https://pastebin.com/aLPT5qAc)
# Part 1
Steps to reproduce:
1. Place an empty Gas Output Port block
2. Place any filled Mekanism Chemical/Gas tank
3. Connect with Mekanism pressurized pipes (the ones that transmit gasses)

What I expected to happen:
Nothing.

What happened instead:
The Gas Output block filled with the gas.

# Part 2
Steps to reproduce:
1. Place any filled Gas Output Port block
2. Place an empty Mekanism Chemical/Gas tank
3. Connect with Mekanism pressurized pipes (the ones that transmit gasses)

What I expected to happen:
Mekanism Chemical/Gas tank to fill.

What happened instead:
Nothing.

**Comment by ticticboooom** [comment]
the output ports do NOT (yet) push into nearby inventories, i believe this is your issue

**Comment by jgrimes900** [comment]
I'm saying it doesn't push into the pipe.

**Comment by ticticboooom** [comment]
that is what i said, that is not yet implemented

**Comment by jgrimes900** [comment]
Okay, I thought you misinterpreted that it wasn't going directly into the tank.

**Comment by ticticboooom** [comment]
noooo pipes are inventories also, they just move things around also, just to clarify my thoughts :)

Closing due to this already being in the todo list
