### ISSUE TITLE
[CRASH] Game crash when recipe use Mekanism infuse type

### ISSUE THREAD

**Issue by Valgrifer** [TicTicBoooom-Mods/MasterfulMachinery#27]
# Version Information
Forge version:  36.2.4
Masterful Machinery version: MasterfulMachinery-1.16.5-0.1.57-B850.jar

ADD ON'S
if not installed just put "null"
Optifine version: null
Botania version:  Botania-1.16.5-420.jar
Create version: create-mc1.16.5_v0.3.2f.jar
Mekanism version: Mekanism-1.16.5-10.0.24.453.jar
Pneumaticcraft version: null
Astral Sorcery version: null

# Further Information
Link to crash-report: (https://gist.github.com/Valgrifer/0779570c7b2d3eafa2dcfe9b3624c7cf)
Steps to reproduce:
1. build a mm structure
2. make a recipe with infuse type
3. do the recipe
4. game crash

What I expected to happen:
Let the recipe do.

What happened instead:
The Game was crashed.

**Comment by MasterSloth1** [comment]
please post your controller and recipe file

**Comment by Valgrifer** [comment]
recipe make in kubejs: https://gist.github.com/Valgrifer/b19098fb59b76966253b8e8279177d28
controller : https://gist.github.com/Valgrifer/3c7c655ca024f8e18014f6a358888419

**Comment by MasterSloth1** [comment]
line 42 of your recipe script you have gas instead of infuse
```json
		{
			"type": "masterfulmachinery:mekanism_infuse",
			"data": {
				"infuse": "mekanism:refined_obsidian",
				"amount": 159644
			}
		}
```

**Comment by Valgrifer** [comment]
fixing but it still crash

**Comment by Frinn38** [comment]
look like a typo
https://github.com/TicTicBoooom-Mods/MasterfulMachinery/blob/754fa9e234cd5dfaa1fcfdc47388bce1e6f1c81e/src/main/java/com/ticticboooom/mods/mm/ports/state/MekInfusePortState.java#L51-L52

**Comment by Valgrifer** [comment]
well yes it can't work xD
good fix ^^

**Comment by ticticboooom** [comment]
please can you provide your structure recipe, and elaborate IN-DETAIL on how to reproduce the issue

**Comment by ticticboooom** [comment]
> look like a typo
> 
> https://github.com/TicTicBoooom-Mods/MasterfulMachinery/blob/754fa9e234cd5dfaa1fcfdc47388bce1e6f1c81e/src/main/java/com/ticticboooom/mods/mm/ports/state/MekInfusePortState.java#L51-L52

you found the exact issue, much appreciated on the find :)
