### ISSUE TITLE
[BUG] Unable to extract energy from energy output port

### ISSUE THREAD

**Issue by kemikalgirl** [TicTicBoooom-Mods/MasterfulMachinery#31]
# Version Information
Forge version:  36.2.22
Masterful Machinery version: 1.16.5-0.1.60

## Add-ons
Optifine version: null
Botania version:  null
Create version: 0.3.2g
Mekanism version: 10.1.0
Pneumaticcraft version: null
Astral Sorcery version: null

# Further Information
Steps to reproduce:
1. Assemble a machine which outputs RF energy;
2. Try any way to extract energy from its energy output port (connect wires from Immersive Engineering, Mekanism, Create Addition, place near it any energy storage from these mods — nothing should work).

What I expected to happen:
The energy port to output the energy.

What happened instead:
The energy port didn't output the energy.

**Comment by MasterSloth1** [comment]
duplicate issue https://github.com/TicTicBoooom-Mods/MasterfulMachinery/issues/12
ports dont auto push their result to neighboring accepting blocks
