### ISSUE TITLE
[BUG] Crash when JEI Rendering of structure

### ISSUE THREAD

**Issue by DariusSG** [TicTicBoooom-Mods/MasterfulMachinery#33]
# Version Information
Forge version:  1.16.5 
Masterful Machinery version: 0.1.60

ADD ON'S
Mekanism version: 10.1.2.457

# Further Information
Link to latest.log: [lastest.log (2020-03-23)](https://gist.github.com/DariusSG/8ee0704846423d2368073d83f52b5adf)
Link to crash.log: [crash-2022-03-23_23.40.16-client.txt](https://gist.github.com/DariusSG/c378f107515f4c5c91ddde65822d165d)
Steps to reproduce:
1. Press "U" on the blueprint to see the structure

What I expected to happen:
The rendering of the structure

What happened instead:
Crash of the world (full game crash prevented by Not Enough Crashes)

Structure file : [distillation_tower.json](https://gist.github.com/DariusSG/9db09f0f878256c35c2e02f9f57291f7)

**Comment by Dovahkill** [comment]
Try with latest beta version (0.1.61) of MM. (Manual download in curseforge  in versions tab)
