### ISSUE TITLE
Have some problems 

### ISSUE THREAD

**Issue by MrLaCar** [TicTicBoooom-Mods/MasterfulMachinery#44]
I wonder what time this mod will be published in Minecraft(version 1.19.2)or any other version 1.19.

The other problem is when I creating a new structure of machine,I want to create a port and name it as “small item port” but it has different color with other machine, Dose there any ways can change the color of the port I created into the different colors when in different structures just like Gregtech.

**Comment by ticticboooomer** [comment]
sorry cannot give eta

**Comment by MasterSloth1** [comment]
the only way i can think of doing this is by using optifines texture system, im not really sure how to do it but i know you can set a texture based on surrounding blocks im pretty sure optifine adds this feature, maybe look into this as MM does not add anything like this with out creating a new port for each structure
This is all that MM adds - https://docs.ticticboooom.com/masterfulmachinery/rewrite/recource_pack/
