### ISSUE TITLE
Game crashed.

### ISSUE THREAD

**Issue by liuseniubi** [TicTicBoooom-Mods/MasterfulMachinery#6]
I don't what caused this problem.
The crash-report is here.
https://paste.ubuntu.com/p/C35KvQBtFx/

**Comment by MasterSloth1** [comment]
can you post your log file please

**Comment by liuseniubi** [comment]
latest.log:https://paste.ubuntu.com/p/2rhcVPCNnd/

**Comment by MasterSloth1** [comment]
this is a error todo with craft tweaker not Masterful Machinery, please take it over to their github and request assistance their :D

**Comment by liuseniubi** [comment]
Oh, I made a mistake, the log I update is wrong.

**Comment by liuseniubi** [comment]
https://paste.ubuntu.com/p/BtPYqw9GtM/

**Comment by ticticboooom** [comment]
as we said this is not an error with MM and is an issue with possibly craft tweaker

**Comment by liuseniubi** [comment]
Okay, Thank all of yours!
