### ISSUE TITLE
1.16.5-0.1.38-B22

### ISSUE THREAD

**Issue by realTIMematrix** [TicTicBoooom-Mods/MasterfulMachinery#8]
Mod still requires AstralSorcery.

	Mod File: MasterfulMachinery-1.16.5-0.1.38-B22.jar
	Failure message: Masterful Machinery (masterfulmachinery) has failed to load correctly
		java.lang.NoClassDefFoundError: hellfirepvp/astralsorcery/common/block/base/BlockStarlightRecipient
	Mod Version: 1.16.5-0.1.38-B22
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ClassNotFoundException: hellfirepvp.astralsorcery.common.block.base.BlockStarlightRecipient

Please remove this required dependency because I don't want to use AS in my modpack.

**Comment by MasterSloth1** [comment]
working on it thanks

**Comment by ticticboooom** [comment]
fixed in latest 0.1.40
