### ISSUE TITLE
Recipe shows up in jei but doesn't work in-game

### ISSUE THREAD

**Issue by Rozen-Hartmann** [TicTicBoooom-Mods/MasterfulMachinery#9]
Recipe script:
```js
events.listen('recipes', (event) => {
event.custom({
    "type": "masterfulmachinery:machine_process",
    "structureId": "ethylene_reactor",
    "controllerId": "basic",
    "ticks": 100,
    "inputs": [
        {
            "type": "masterfulmachinery:mekanism_gas",
            "data":{
                "gas": "mekanism:ethene",
                "amount": 500
            }
		},
		{
            "type": "masterfulmachinery:mekanism_gas",
            "data":{
                "gas": "mekanism:oxygen",
                "amount": 250
            }
		},
		{
            "type": "masterfulmachinery:energy",
            "data":{
                "amount": 800
            }
	    }
    ],
    "outputs":[
        {
            "type": "masterfulmachinery:mekanism_gas",
            "data":{
                "gas": "kubejs:ethylene_oxide_gas",
                "amount": 1000
            }
        }
    ]
})
});

```

**Comment by MasterSloth1** [comment]
please upload structure file and controller file and answer the following questions :D
forge version - 
mod version - 
is optifine installed? - 
astral sorcery installed? - 
create installed? - 
mekanism installed? - 
pneumaticcraft installed? - 
botania installed? -

**Comment by Rozen-Hartmann** [comment]
forge 36.1.13
masterful machinery 0.1.30
no optifine and no pneumaticcraft
AS, create, mekanism and botania are installed

structure script(changed the extension to .txt for convinience)

[ethylene_reactor.txt](https://github.com/TicTicBoooom-Mods/MasterfulMachinery/files/6534526/ethylene_reactor.txt)

controller config:

{
  "controllerId": "basic",
  "name": "Basic",
  "ports": [
    {
      "type": "masterfulmachinery:items",
      "name": "Basic Item",
      "id": "basic",
      "data": {
        "rows": 3,
        "columns": 3
      }
    },
    {
      "type": "masterfulmachinery:energy",
      "name": "Basic Energy",
      "id": "chungus",
      "data": {
        "capacity": 1000000000
      }
    },
    {
      "type": "masterfulmachinery:fluids",
      "name": "Small Fluid",
      "id": "small",
      "data": {
        "capacity": 10000
      }
    },
    {
      "type": "masterfulmachinery:mekanism_gas",
      "name": "Gassy",
      "id": "gassy",
      "data": {
        "capacity": 100000
      }
    },
    {
      "type": "masterfulmachinery:mekanism_slurry",
      "name": "MekSlurry",
      "id": "mekslurry",
      "data": {
        "capacity": 1000000
      }
    }
  ]
}

**Comment by Rozen-Hartmann** [comment]
I just updated masterful machinery to 1.52-B171 and everything works. Thanks!
